// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "Extension.eb78aa63-702f-4de0-9fe8-3a6b5cebb723";
        public const string Name = "String Localizer";
        public const string Description = @"The faster way to add strings to your resx files.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "lsoft";
        public const string Tags = "resx";
        public const bool IsPreview = false;
    }
}
