// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Extension
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string StringLocalizerString = "c8d8d45f-f485-4c8d-beb8-3774dee9dcc3";
        public static Guid StringLocalizer = new Guid(StringLocalizerString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ExtensionMenuGroup = 0x1001;
        public const int SubExtensionMenuGroup = 0x1002;
        public const int AddStringToResourceCommandId = 0x1003;
        public const int SubExtensionMenu = 0x1004;
    }
}
